spring:
  profiles:
    active: dev
  application:
    name: game-portfolio-backend
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true